# Generated by Django 5.1.3 on 2024-11-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaxaq',
            name='name_en',
            field=models.CharField(max_length=50, null=True, verbose_name='qaxaqi anun'),
        ),
        migrations.AddField(
            model_name='qaxaq',
            name='name_hy',
            field=models.CharField(max_length=50, null=True, verbose_name='qaxaqi anun'),
        ),
        migrations.AddField(
            model_name='qaxaq',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='qaxaqi anun'),
        ),
    ]
