# Generated by Django 5.1.3 on 2024-11-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_qaxaq_name_en_qaxaq_name_hy_qaxaq_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mayla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Mayla')),
                ('name_hy', models.CharField(max_length=50, null=True, verbose_name='Mayla')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Mayla')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Mayla')),
                ('img', models.ImageField(null=True, upload_to='Mayla', verbose_name='Mayli nkary')),
                ('mayla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mayla', to='main.qaxaq')),
            ],
        ),
        migrations.CreateModel(
            name='Poxoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='poxoci anun')),
                ('name_hy', models.CharField(max_length=50, null=True, verbose_name='poxoci anun')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='poxoci anun')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='poxoci anun')),
                ('poxoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Poxoc', to='main.mayla')),
            ],
        ),
    ]
