# Generated by Django 5.1.3 on 2024-11-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_poxoc_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mayla',
            old_name='mayla',
            new_name='Qaxaq',
        ),
        migrations.RenameField(
            model_name='poxoc',
            old_name='poxoc',
            new_name='Mayla',
        ),
    ]
